blog/urls.py
from django.urls import re_path
from django.views.generic import ListView, DateDetailView

from blog.models import Post


app_name = 'blog'


urlpatterns = [
    re_path(
        r'^$',
        ListView.as_view(queryset=Post.objects.published(), paginate_by=3),
        name='post-list'),
    re_path(
        r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        DateDetailView.as_view(date_field="publish", model=Post),
        name='post-detail')
]

tutorial/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'blog/', include('blog.urls', namespace='blog')),
    path(r'', TemplateView.as_view(template_name="home.html"),
        name='homepage'),
    path(r'comments/', include('django_comments_xtd.urls')),

]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
# django comments
from django_comments_xtd.moderation import moderator, SpamModerator
from blog.badwords import badwords
  
class PostManager(models.Manager):
    def published(self):
        return self.get_queryset().filter(status="PUB",
                                          publish__lte=timezone.now())


class Post(models.Model):
    STATUS_CHOICES = (
        ('DRAFT', 'Draft'),
        ('PUB', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    status = models.CharField(max_length=5, choices=STATUS_CHOICES,
                              default="DRAFT")
    allow_comments = models.BooleanField('allow comments', default=True)
    publish = models.DateTimeField(default=timezone.now)
    objects = PostManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       kwargs={'year': self.publish.year,
                               'month': self.publish.strftime('%b'),
                               'day': self.publish.strftime('%d'),
                               'slug': self.slug})

# django comments app

class PostCommentModerator(SpamModerator):
    email_notification = True

    def moderate(self, comment, content_object, request):
        # Make a dictionary where the keys are the words of the message
        # and the values are their relative position in the message.
        def clean(word):
            ret = word
            if word.startswith('.') or word.startswith(','):
                ret = word[1:]
            if word.endswith('.') or word.endswith(','):
                ret = word[:-1]
            return ret

        lowcase_comment = comment.comment.lower()
        msg = dict([(clean(w), i)
                    for i, w in enumerate(lowcase_comment.split())])
        for badword in badwords:
            if isinstance(badword, str):
                if lowcase_comment.find(badword) > -1:
                    return True
            else:
                lastindex = -1
                for subword in badword:
                    if subword in msg:
                        if lastindex > -1:
                            if msg[subword] == (lastindex + 1):
                                lastindex = msg[subword]
                        else:
                            lastindex = msg[subword]
                    else:
                        break
                if msg.get(badword[-1]) and msg[badword[-1]] == lastindex:
                    return True
        return super(PostCommentModerator, self).moderate(comment,
                                                          content_object,
                                                          request)

moderator.register(Post, PostCommentModerator)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}django-comments-xtd tutorial{% endblock %}</title>
    <link 
      rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" 
      integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" 
      crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      .container {
        width: auto;
        max-width: 680px;
        padding: 0 15px;
      }
      .post-footer, .comments {
        padding: 20px 0;
      }
    </style>    
  </head>
  <body>
    <div class="container">
      <div class="row my-4">
        <div class="col-lg-12">
	      <h5 class="text-center">django-comments-xtd</h5>
          <hr/>
        </div>
      </div>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <hr/>
          <p class="text-center text-muted small">django-comments-xtd tutorial.</p>
        </div>
      </div>
    </div>

    {% block extra-js %}
    {% endblock %}
  </body>
</html>

templates/blog/post_detail.html
{% extends "base.html" %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="pb-3">
  <h1 class="page-header text-center">{{ object.title }}</h1>
  <p class="small text-center">{{ object.publish|date:"l, j F Y" }}</p>
</div>
<div>
  {{ object.body|linebreaks }}
</div>

{% get_comment_count for object as comment_count %}
<div class="py-4 text-center">
  <a href="{% url 'blog:post-list' %}">Back to the post list</a>
  &nbsp;&sdot;&nbsp;
  {{ comment_count }} comment{{ comment_count|pluralize }}
  ha{{ comment_count|pluralize:"s,ve"}} been posted.
</div>

{% if object.allow_comments %}
<div class="comment mt-3 mb-5">
  <h4 class="text-center mb-4">Your comment</h4>
  <div class="card pt-4">
    {% render_comment_form for object %}
  </div>
</div>
{% endif %}

{% if comment_count %}
<ul class="media-list">
  {% render_xtdcomment_tree for object allow_flagging allow_feedback show_feedback %}
</ul>

{% endif %}
{% endblock %}


{% block extra-js %}
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  crossorigin="anonymous"></script>
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
  integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"></script>
<script>
  $(function() {
    $('[data-toggle="tooltip"]').tooltip({html: true});
  });
</script>
{% endblock %}

templates/blog/post_list.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<h1 class="pb-3 text-center">Blog</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    {% for object in object_list %}
    <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
    
    {% get_comment_count for object as comment_count %}
    <p class="date">Published {{ object.publish }}</p>
    {{ object.body|truncatewords:30|linebreaks }}
    {% endfor %}
  </div>
</div>

<ul class="mt-5 pagination justify-content-center">
  <li class="page-item{% if not page_obj.has_previous %} disabled{% endif %}">
    <a class="page-link" href="{{ url }}?page={% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}">previous</a>
  </li>
  {% for page_number in page_range %}
  <li class="page-item{% if page_number == page_obj.number %} active{% endif %}">
    <a class="page-link" href="{{ url }}?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% endfor %}
  <li class="page-item{% if not page_obj.has_next %} disabled{% endif %}">
    <a class="page-link" href="{{ url }}?page={% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}">next</a>
  </li>
</ul>
{% endblock %}

templates/comments/400-debug.html
{% extends "base.html" %}

{% block title %}Bad request{% endblock %}

{% block content %}
<h3 class="text-center">Comment post not allowed</h3>
<p class="text-center">{{ why }}</p>
<hr/>
<p class="col-lg-offset-1 col-md-offset-1 text-muted">
  You're seeing this error because you have <code>DEBUG = True</code> in
  your Django settings file. Change that to <code>False</code>, and Django
  will display a standard 400 error page.
</p>
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
<h1 class="pb-3 text-center">tutorial</h1>

<div class="row justify-content-center flex-fill">
  <div class="col-md-10">
    <p class="lead">Contains a simple <code>blog</code> application with a <code>Post</code> model to which we will add comments by using <strong>django-contrib-comments</strong> and <strong>django-comments-xtd</strong>.</p>
    <p class="my-3 text-center">Continue to the <a href="{% url 'blog:post-list' %}">blog</a>.</p>
  </div>
</div>
{% endblock %}